name: Cleanup Old News Folders

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone repository
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo
        cd repo
        git checkout main

    - name: Run cleanup script
      working-directory: repo
      run: |
        python - <<EOF
        import os
        import shutil
        from datetime import datetime, timedelta

        # Define the directory and cutoff time
        news_dir = "News"
        cutoff_time = datetime.now() - timedelta(days=7)

        # Iterate through subdirectories
        for folder in os.listdir(news_dir):
            folder_path = os.path.join(news_dir, folder)
            if os.path.isdir(folder_path):
                # Get folder's last modified time
                last_modified_time = datetime.fromtimestamp(os.path.getmtime(folder_path))

                # Delete the folder if it's older than the cutoff time
                if last_modified_time < cutoff_time:
                    print(f"Deleting outdated folder: {folder_path}")
                    shutil.rmtree(folder_path)
        EOF

    - name: Commit and push changes
      working-directory: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git add .
        git commit -m "Cleanup: Remove outdated News folders"
        git push
